'use client';

import { useState } from 'react';

const fields = { game: [['title', 'Title'], ['status', 'Status'], ['genre', 'Genre'], ['rating', 'Rating'], ['summary', 'Summary'], ['poster', 'Poster link']], anime: [['title', 'Title'], ['episodes', 'Episodes'], ['seasons', 'Seasons'], ['studio', 'Studio'], ['genre', 'Genre'], ['status', 'Status'], ['rating', 'Rating'], ['summary', 'Summary'], ['poster', 'Poster link']], show: [['title', 'Title'], ['language', 'Language'], ['genre', 'Genre'], ['rating', 'Rating'], ['summary', 'Summary'], ['poster', 'Poster link']], character: [['name', 'Name'], ['franchise', 'Franchise'], ['quote', 'Quote'], ['rating', 'Rating'], ['image', 'Image link'], ['note', 'Prashant note']] };

export default function AdminEntryForm({ kind }) {
  const [message, setMessage] = useState('');
  async function submit(event) { event.preventDefault(); setMessage('Saving to archive…'); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const response = await fetch('/api/archive', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...values, kind, hallOfFame: values.hallOfFame === 'on' }) }); const payload = await response.json(); if (response.ok) { setMessage(`${payload.name} is now part of the permanent archive.`); event.currentTarget.reset(); } else setMessage(payload.error || 'Could not save this entry.'); }
  return <form className="admin-card" onSubmit={submit}><div className="form-grid">{fields[kind].map(([name, label]) => <div className={`form-field ${['summary'].includes(name) ? 'full' : ''}`} key={name}><label htmlFor={`${kind}-${name}`}>{label}</label>{name === 'summary' ? <textarea className="form-input" id={`${kind}-${name}`} name={name} placeholder={`Add a concise ${kind} summary…`} /> : <input className="form-input" id={`${kind}-${name}`} name={name} placeholder={label === 'Rating' ? '9.0' : `Enter ${label.toLowerCase()}`} required={['title', 'name'].includes(name)} />}</div>)}{kind !== 'character' && <label className="form-check full"><input type="checkbox" name="hallOfFame" /> Add to Hall of Fame</label>}</div><button className="btn btn-primary" type="submit" style={{ marginTop: 20 }}>Save permanent entry</button>{message && <div className="success-message">{message}</div>}</form>;
}