'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import CaseCard from '../../components/CaseCard';
import CharacterCard from '../../components/CharacterCard';
import TitleDetail from '../../components/TitleDetail';
import { ALL_TITLES, about, characters, getCharactersForTitle, getHallOfFame, getRelatedTitles, getQuotesForTitle, getStats, quotes } from '../../lib/data';

const categoryInfo = { games: ['Games', 'The complete game shelf — from nostalgic classics to worlds still waiting.', 'var(--red)'], anime: ['Anime', 'Long arcs, sharp philosophies, and worlds that refuse to let go.', 'var(--purple)'], shows: ['Shows', 'Prestige drama, crime sagas and the series that owned the weekend.', '#7891ee'], horror: ['Horror', 'The unsettling, the strange, and the stories best watched after dark.', '#df8b67'] };

function Header({ eyebrow, title, description }) { return <div className="page-header"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>; }

function LibraryPage({ category }) {
  const [filter, setFilter] = useState('All'); const [query, setQuery] = useState('');
  const titles = category === 'library' ? ALL_TITLES : ALL_TITLES.filter((title) => title.category === category);
  const statuses = ['All', ...new Set(titles.map((title) => title.status).filter(Boolean))];
  const filtered = titles.filter((title) => (filter === 'All' || title.status === filter) && (!query || `${title.title} ${title.summary} ${(title.genre || []).join(' ')}`.toLowerCase().includes(query.toLowerCase())));
  const info = categoryInfo[category] || ['Library', 'Every title in one cinematic archive, organised into shelves.', 'var(--red)'];
  return <div className="page-shell"><Header eyebrow={category === 'library' ? 'All shelves' : 'Archive shelf'} title={info[0]} description={info[1]} /><div className="archive-toolbar">{statuses.map((status) => <button className={`chip ${filter === status ? 'active' : ''}`} key={status} onClick={() => setFilter(status)}>{status === 'All' ? 'Everything' : status}</button>)}<input className="toolbar-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search this shelf..." aria-label="Search this shelf" /></div><div className="result-count">{filtered.length} entries · Click a card to flip it</div>{filtered.length ? <div className="archive-grid">{filtered.map((title) => <CaseCard key={title.id} title={title} />)}</div> : <div className="empty-state">No entries match that search.</div>}</div>;
}

function HallOfFamePage() {
  const hof = getHallOfFame().sort((a, b) => (b.rating_external_num || 0) - (a.rating_external_num || 0)); const spotlight = hof[0];
  return <div className="page-shell"><Header eyebrow="The legendary shelf" title="Hall of Fame" description="Not everything makes it here. These are the titles that earned a permanent gold border in the MAD WORLD archive." /><div className="hof-hero"><div className="spotlight-card" style={{ backgroundImage: `url(${spotlight?.cover_url || '/images/hero-bg.jpg'})` }}><div className="spotlight-copy"><span className="eyebrow">Archive spotlight · #1</span><h2>{spotlight?.title}</h2><p>{spotlight?.summary}</p><Link href={`/${spotlight?.category}/${spotlight?.slug}`} className="text-link">Open legendary entry →</Link></div></div><div className="ranking-stack">{hof.slice(0, 4).map((title, index) => <Link href={`/${title.category}/${title.slug}`} className="ranked-item" key={title.id}><span className="rank-number">#{index + 1}</span><img src={title.cover_url || '/images/hero-bg.jpg'} alt="" /><div><strong>{title.title}</strong><small>{title.category} · {title.rating_external || 'Unrated'}</small></div></Link>)}</div></div><div className="archive-grid">{hof.map((title) => <CaseCard key={title.id} title={title} />)}</div></div>;
}

function CharactersPage() { const [query, setQuery] = useState(''); const shown = characters.filter((character) => `${character.name} ${character.franchise} ${character.type}`.toLowerCase().includes(query.toLowerCase())); return <div className="page-shell"><Header eyebrow="The faces behind the stories" title="Characters" description="Collectible profiles for the heroes, villains, mentors and chaos agents who made these worlds matter." /><div className="archive-toolbar"><input className="toolbar-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search characters..." aria-label="Search characters" /></div><div className="characters-grid">{shown.map((character) => <CharacterCard key={character.id} character={character} />)}</div></div>; }

function QuotesPage() { const [query, setQuery] = useState(''); const [category, setCategory] = useState('All'); const filtered = quotes.filter((quote) => (category === 'All' || quote.category_ref === category) && `${quote.text} ${quote.title_name}`.toLowerCase().includes(query.toLowerCase())); const random = quotes[Math.floor(quotes.length / 2)]; return <div className="page-shell"><Header eyebrow="Words worth repeating" title="Quote room" description="The lines that echo after the credits. Search by title, filter by world, and keep the good ones close." /><div className="quotes-hero glass-card"><span className="eyebrow">Random archive pull</span><blockquote>“{random?.text}”</blockquote><span className="quote-credit">{random?.title_name} · {random?.category_ref}</span></div><div className="archive-toolbar">{['All', 'games', 'anime', 'shows'].map((item) => <button key={item} className={`chip ${category === item ? 'active' : ''}`} onClick={() => setCategory(item)}>{item}</button>)}<input className="toolbar-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search quotes..." aria-label="Search quotes" /></div><div className="quote-grid">{filtered.map((quote) => <Link href={`/${quote.category_ref}/${quote.title_slug}`} className="quote-card" key={quote.id}><p>“{quote.text}”</p><footer><b>{quote.title_name}</b><br />{quote.category_ref}</footer></Link>)}</div></div>; }

function AboutPage() { const stats = getStats(); return <div className="page-shell"><Header eyebrow="Behind the archive" title="About MAD WORLD" description="A personal entertainment archive built from the stories that shaped one gamer, viewer and lifelong explorer." /><div className="about-grid"><aside className="about-card profile-card"><div className="avatar" /><span className="eyebrow">Curator / explorer</span><h2>Prashant</h2><p>{about.short_bio}</p><div className="social-list">{(about.social || []).map((social) => <a className="social-pill" key={social.url} href={social.url.trim()} target="_blank" rel="noreferrer">{social.label.replace(':', '')}</a>)}</div></aside><article className="about-story"><span className="eyebrow">The personal story</span><h2>Why MAD WORLD exists</h2><p>{about.website_bio}</p><p>Every entry is a small time capsule: a late-night gaming session, a quote saved in a notes app, a character who changed the way a story landed. MAD WORLD turns those fragments into a place that can keep growing.</p><div className="about-stats">{[['Games', stats.games], ['Anime', stats.anime], ['Shows', stats.shows], ['Characters', stats.characters]].map(([label, number]) => <div className="about-stat" key={label}><strong>{number}</strong><span>{label}</span></div>)}</div><div className="social-list">{about.franchises.split(', ').map((franchise) => <span className="social-pill" key={franchise}>{franchise}</span>)}</div></article></div></div>; }

function CourtPage() { const [winner, setWinner] = useState('Kratos'); const first = characters.find((character) => character.name === 'Kratos') || characters[0]; const second = characters.find((character) => character.name === 'Johan Liebert') || characters[1]; const champion = winner === first.name ? first : second; return <div className="page-shell"><Header eyebrow="The tournament of taste" title="Character Court" description="Two icons enter. One champion leaves. A playful ranking room for the characters who own the scene." /><div className="court-layout"><div className="court-panel"><span className="eyebrow">Current matchup</span><div className="fighter"><img src={first.cover_url} alt="" /><div><strong>{first.name}</strong><small>{first.franchise}</small></div><button className="chip" onClick={() => setWinner(first.name)}>Vote</button></div><div className="versus">VS</div><div className="fighter"><img src={second.cover_url} alt="" /><div><strong>{second.name}</strong><small>{second.franchise}</small></div><button className="chip" onClick={() => setWinner(second.name)}>Vote</button></div></div><div className="champion"><span className="eyebrow">Champion screen</span><img src={champion.cover_url} alt={champion.name} /><h2>{champion.name}</h2><p>{champion.bio}</p><div className="success-message">Current crowd favourite · {champion.franchise}</div></div></div><div className="court-panel" style={{ marginTop: 20 }}><span className="eyebrow">Court history</span><h2 style={{ marginTop: 10 }}>The archive remembers the winners.</h2><p style={{ color: 'var(--muted)', marginTop: 10 }}>Every matchup is a snapshot of taste — revisit the court whenever a new legend enters the archive.</p></div></div>; }

function AdminPage() { const [saved, setSaved] = useState(false); function submit(event) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget).entries()); const current = JSON.parse(localStorage.getItem('mad-world-custom-titles') || '[]'); localStorage.setItem('mad-world-custom-titles', JSON.stringify([...current, { ...data, id: `custom-${Date.now()}` }])); setSaved(true); event.currentTarget.reset(); } return <div className="page-shell"><Header eyebrow="Curator tools" title="Add a title" description="A local-first intake form for future entries. Save a new title in this browser without editing the source data." /><form className="admin-card" onSubmit={submit}><div className="form-grid">{[['name','Name','The Last of Us'],['title','Title type','Game / Anime / Show'],['genre','Genre','Drama, Adventure'],['rating','Rating','9.5'],['poster','Poster link','/posters/games/...']].map(([name,label,placeholder]) => <div className="form-field" key={name}><label htmlFor={name}>{label}</label><input className="form-input" id={name} name={name} placeholder={placeholder} required={name === 'name'} /></div>)}<div className="form-field"><label htmlFor="status">Status</label><select className="form-input" id="status" name="status" defaultValue="Owned / Played"><option>Owned / Played</option><option>Watched / In Progress</option><option>Want to Watch</option><option>Want to Play</option></select></div><div className="form-field full"><label htmlFor="summary">Summary</label><textarea className="form-input" id="summary" name="summary" placeholder="Why does this story belong in the archive?" /></div><div className="form-field"><label htmlFor="quote">Famous quote</label><input className="form-input" id="quote" name="quote" placeholder="A line worth keeping" /></div><div className="form-field"><label htmlFor="note">Prashant note</label><input className="form-input" id="note" name="note" placeholder="Your personal note" /></div><label className="form-check full"><input type="checkbox" name="hallOfFame" /> Add this title to Hall of Fame</label></div><button className="btn btn-primary" type="submit" style={{ marginTop: 20 }}>Save to local archive</button>{saved && <div className="success-message">Saved locally. Your new entry is ready for the next data sync.</div>}</form></div>; }

function SearchPage() { const [query, setQuery] = useState(''); return <div className="page-shell"><Header eyebrow="Archive search" title="Find a story" description="Search across every title, world and genre in MAD WORLD." /><input autoFocus className="toolbar-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try God of War, crime, fantasy..." aria-label="Search all entries" /><div className="result-count">{ALL_TITLES.filter((title) => `${title.title} ${title.summary} ${(title.genre || []).join(' ')}`.toLowerCase().includes(query.toLowerCase())).length} matches</div><div className="archive-grid">{ALL_TITLES.filter((title) => `${title.title} ${title.summary} ${(title.genre || []).join(' ')}`.toLowerCase().includes(query.toLowerCase())).slice(0, 30).map((title) => <CaseCard key={title.id} title={title} />)}</div></div>; }

function DetailPage({ category, slug }) { const title = ALL_TITLES.find((entry) => entry.category === category && entry.slug === slug); if (!title) return <div className="page-shell"><Header eyebrow="404" title="Entry not found" description="This story has not been catalogued yet." /><Link href={`/${category}`} className="btn btn-ghost">Back to shelf</Link></div>; return <TitleDetail title={title} characters={getCharactersForTitle(title.id)} related={getRelatedTitles(title)} quotes={getQuotesForTitle(title.id)} />; }

export default function ArchiveRoute({ params }) { const route = params?.slug || []; const primary = route[0]; if (route.length > 1 && ['games','anime','shows','horror','characters'].includes(primary)) return primary === 'characters' ? <div className="page-shell"><Header eyebrow="Character file" title={route[1].replaceAll('-', ' ')} description="A character entry from the MAD WORLD archive." /></div> : <DetailPage category={primary} slug={route[1]} />; if (primary === 'hall-of-fame') return <HallOfFamePage />; if (primary === 'characters') return <CharactersPage />; if (primary === 'quotes') return <QuotesPage />; if (primary === 'about') return <AboutPage />; if (primary === 'character-court') return <CourtPage />; if (primary === 'admin' && route[1] === 'add-title') return <AdminPage />; if (primary === 'search') return <SearchPage />; if (primary === 'library') return <LibraryPage category="library" />; if (categoryInfo[primary]) return <LibraryPage category={primary} />; return <LibraryPage category="library" />; }